name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: |
          ls ${{ github.workspace }}
      - run: cd ..
      - name: build and testing
        with:
          context: .
        run: docker build . -f Dockerfile -t fse_test
